stop the service after tests completed

diff --git a/.github/workflows/run_question_service_integration_tests.yml b/.github/workflows/run_question_service_integration_tests.yml
--- a/.github/workflows/run_question_service_integration_tests.yml
+++ b/.github/workflows/run_question_service_integration_tests.yml
@@ -36,6 +36,8 @@ jobs:
         run: |
           cd backend/user-service
           npm run dev &
+          # Capture the process ID (PID) of the service
+          USER_SERVICE_PID=$!
         env:
           DATABASE_URL: ${{ secrets.TEST_DATABASE_URL }}
           SERVICE_PORT: 5005
@@ -44,6 +46,8 @@ jobs:
         run: |
           cd backend/auth-service
           npm run dev &
+          # Capture the process ID (PID) of the service
+          AUTH_SERVICE_PID=$!
         env:
           DATABASE_URL: ${{ secrets.TEST_DATABASE_URL }}
           SERVICE_PORT: 5050
@@ -52,25 +56,29 @@ jobs:
       - name: Wait for services to start
         run: |
           timeout=60
-              until curl --output /dev/null --silent --head --fail http://localhost:5050/auth/api/health; do
-              echo 'Waiting for Auth Service to start...'
-              sleep 1
-              ((timeout--))
-              if [ $timeout -eq 0 ]; then
-                  echo 'Auth Service failed to start'
-                  exit 1
-              fi
+          until curl --output /dev/null --silent --head --fail http://localhost:5050/auth/api/health; do
+            echo 'Waiting for Auth Service to start...'
+            sleep 1
+            ((timeout--))
+            if [ $timeout -eq 0 ]; then
+              echo 'Auth Service failed to start'
+              # Terminate Auth Service
+              kill $AUTH_SERVICE_PID
+              exit 1
+            fi
           done
 
           timeout=60
-              until curl --output /dev/null --silent --head --fail http://localhost:5005/user/api/health; do
-              echo 'Waiting for User Service to start...'
-              sleep 1
-              ((timeout--))
-              if [ $timeout -eq 0 ]; then
-                  echo 'User Service failed to start'
-                  exit 1
-              fi
+          until curl --output /dev/null --silent --head --fail http://localhost:5005/user/api/health; do
+            echo 'Waiting for User Service to start...'
+            sleep 1
+            ((timeout--))
+            if [ $timeout -eq 0 ]; then
+              echo 'User Service failed to start'
+              # Terminate User Service
+              kill $USER_SERVICE_PID
+              exit 1
+            fi
           done
 
       - name: Run Integration Tests
@@ -84,3 +92,10 @@ jobs:
           TEST_ADMIN_PASSWORD: ${{ secrets.TEST_ADMIN_PASSWORD }}
           TEST_USER_EMAIL: ${{ secrets.TEST_USER_EMAIL }}
           TEST_USER_PASSWORD: ${{ secrets.TEST_USER_PASSWORD }}
+
+      # Send a termination signal to stop the services
+      - name: Stop User Service
+        run: kill $USER_SERVICE_PID || true
+
+      - name: Stop Auth Service
+        run: kill $AUTH_SERVICE_PID || true
